 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: Sggp_pretrain

  load_pretrained: True
  pretrained: "null"

  # vit encoder
  vit_type: "base"
  image_size: 224
  patch_size: 16
  vit_embed_dim: 768
  mask_patch_size: 32
  mask_ratio: 0.6


  # bert config
  med_config_path: "configs/models/sggp_text_bert.json"
  unified_med_config_path: "configs/models/sggp_unified_bert.json"
  mlm_mask_prob: 0.15
  detector_config_path: "configs/models/GroundingDINO_SwinB_cfg.py" #"common/models/mask_rcnn_vitdet_pretrain.py"
  embed_dim: 256
  momentum: 0.995
  alpha: 0.4
  temp: 0.07

  max_txt_len: 30


